animal = "  chanCHIto feliz   "
print(animal.upper())
print(animal.lower())
print(animal.capitalize())
print(animal.title())
print(animal.strip())
print(animal.strip().capitalize())
print(animal.lstrip().capitalize())
print(animal.rstrip().capitalize())
print(animal.find("CH"))
print(animal.find("cH"))
print(animal.replace("nCH", "j"))
print("nCH" in animal)
print("nCH" not in animal)
